# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_name', models.CharField(blank=True, max_length=64, verbose_name='机柜名称')),
                ('cabinet_code', models.CharField(blank=True, max_length=64, verbose_name='机柜编号')),
                ('room_id', models.IntegerField(blank=True, verbose_name='机房id')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除')),
            ],
            options={
                'verbose_name': '机柜',
                'verbose_name_plural': '机柜',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='设备名称')),
                ('device_type', models.CharField(blank=True, choices=[('storage', '存储设备'), ('safe', '安全设备')], max_length=32, verbose_name='设备类型')),
                ('brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=32, null=True, verbose_name='型号')),
                ('hardware', models.TextField(blank=True, null=True, verbose_name='硬件信息')),
                ('cabinet_id', models.IntegerField(blank=True, verbose_name='机柜id')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='MachineRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='机房名称')),
                ('room_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='机房编号')),
                ('region_id', models.IntegerField(blank=True, verbose_name='区域id')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='区域')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目')),
                ('manager', models.CharField(blank=True, max_length=32, null=True, verbose_name='管理者')),
                ('service_tag', models.CharField(blank=True, max_length=32, null=True, verbose_name='服务标签')),
                ('server_status', models.CharField(blank=True, choices=[('online', '上线状态'), ('offline', '下线状态'), ('idle', '闲置状态')], max_length=32, null=True, verbose_name='服务器状态')),
                ('server_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='服务器名称')),
                ('environment', models.CharField(blank=True, choices=[('product', '生产环境'), ('develop', '开发环境')], max_length=32, verbose_name='')),
                ('brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=32, null=True, verbose_name='型号')),
                ('assets_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='资产编号')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip地址')),
                ('cabinet_id', models.IntegerField(blank=True, verbose_name='机柜id')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
    ]
